### ISSUE TITLE
When Reboot system kernel module and iptables extension (settings too) gone

### ISSUE THREAD

**Issue by cartals** [LGA1150/netfilter-spooftcp#7]
Hi, im using ubuntu when i do write a command like your usage example it works correctly but when i reboot my computer i must go cd netfilter-spoof and make, sudo make install and do anything again if i don't do these think it says "iptables: no chain/target/match by that name".

**Comment by st1905** [comment]
When you execute the iptables command, the spooftcp extension loads the kernel module automagically. I don`t think that the iptables extension or the kernel module could disappear after a reboot. That does`t make any sense to me.

**Comment by cartals** [comment]
> When you execute the iptables command, the spooftcp extension loads the kernel module automagically. I don`t think that the iptables extension or the kernel module could disappear after a reboot. That does`t make any sense to me.

Abi ben donaimhaberdeki rapht kapatıp açıyorum gidiyor her şey birde bunu archta kullanabilir miyim ?
